// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljnrknhjwayggrpamqhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqbnJrbmhqd2F5Z2dycGFtcWhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MTYzMTMsImV4cCI6MjA3MzA5MjMxM30.foZFklOVN3JDozvbaDHhxaJj0CYzOJ3bU56ZEVBkzPE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});